site_name: My Docs
theme:
  name: material
  features:
      - navigation.tabs
      - navigation.sections
      - toc.integrate
      - navigation.top
      - search.suggest
      - search.highlight
      - content.tabs.link
      - content.code.annotate
      - content.code.copy
      - content.code.select
  language: en
  palette:
      - scheme: default
        toggle:
          icon: material/toggle-switch-off-outline 
          name: Switch to dark mode
        primary: teal
        accent: purple 
      - scheme: slate 
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode    
        primary: teal
        accent: lime
        
repo_url: https://github.com/MaksNick/ITMO_ICT_WebDevelopment_2023-2024
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys

nav:
  - Home: index.md
  - Lab 1:
      - Intro: lab1/index.md
      - Task 1: lab1/task1.md
      - Task 2: lab1/task2.md
      - Task 3: lab1/task3.md
      - Task 4: lab1/task4.md
      - Task 5: lab1/task5.md
  - Lab 2:
    - Intro: lab2/index.md
    - Assessment: lab2/variant.md
    - Models: lab2/models.md
    - Views: lab2/views.md
    - Forms and URLs: lab2/forms.md